version: '3'

servicies:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    parts:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app/
    environment:
      - PYTHONPATH=/code
    networks:
      - philosophy-network

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: dockerfile
    ports:
      - "5432:5432"


  frontend:

  rag:

networks:
  philosophy-network:
    driver: brige