version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app/
      - ./source:/app/source
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    networks:
      - philosophy-network

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    volumes:
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - philosophy-network

networks:
  philosophy-network:
    driver: bridge